
(()=>{'use strict';
const $=id=>document.getElementById(id),ctx=$('map').getContext('2d'),W=9,H=6,C=100,KEY='minigames-kingdom-v04';
const defs={house:{name:'Дом',icon:'🏠',desc:'+6 мест для жителей',cost:{wood:35,gold:20}},farm:{name:'Ферма',icon:'🌾',desc:'Даёт еду, лучше на равнине',cost:{wood:25,gold:20}},lumber:{name:'Лесопилка',icon:'🪓',desc:'Даёт дерево, лучше в лесу',cost:{wood:15,gold:30}},quarry:{name:'Каменоломня',icon:'⛏️',desc:'Даёт камень, лучше в горах',cost:{wood:30,gold:35}},market:{name:'Рынок',icon:'🏪',desc:'Даёт золото за день',cost:{wood:35,stone:15,gold:35}},barracks:{name:'Казармы',icon:'🛡️',desc:'+8 мест в армии',cost:{wood:40,stone:25,gold:35}}};
const resourceNames={gold:'золота',wood:'дерева',stone:'камня',food:'еды'},landNames={plain:'Равнина',forest:'Лес',mountain:'Горы'};
let s,mode='expand',tab='build',build='farm',sel=null,battle=null,unit='inf',logs=[],lastMessage='';
const at=(x,y)=>s.tiles[y*W+x],valid=(x,y)=>x>=0&&y>=0&&x<W&&y<H;
const count=k=>s.tiles.filter(t=>t.owned&&t.building===k).length,owned=()=>s.tiles.filter(t=>t.owned).length,army=()=>s.troops.inf+s.troops.arch+s.troops.cav,housing=()=>8+count('house')*6,armyMax=()=>5+count('barracks')*8;
const near=t=>[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>valid(t.x+dx,t.y+dy)&&at(t.x+dx,t.y+dy).owned);
const afford=c=>Object.entries(c).every(([k,v])=>s[k]>=v),pay=c=>Object.entries(c).forEach(([k,v])=>s[k]-=v),price=c=>Object.entries(c).map(([k,v])=>v+' '+resourceNames[k]).join(', ');
const hirePrice=k=>k==='inf'?{gold:25,food:8}:k==='arch'?{gold:35,wood:8}:{gold:55,food:12};
function message(t){lastMessage=t;$('message').textContent=t}
function log(t){logs.unshift('День '+s.day+': '+t);logs=logs.slice(0,20);$('history').textContent=logs.join('\n')}
function economy(){let out={gold:7-army(),wood:0,stone:0,food:-Math.ceil(s.pop*.8)-army()*2},workers=Math.max(0,s.pop-2);const jobs={farm:['food',24],lumber:['wood',15],quarry:['stone',11],market:['gold',22]};for(const t of s.tiles){if(!t.owned||!jobs[t.building])continue;const [r,base]=jobs[t.building],assigned=Math.min(2,workers);workers-=assigned;const bonus=t.building==='farm'&&t.terrain==='plain'||t.building==='lumber'&&t.terrain==='forest'||t.building==='quarry'&&t.terrain==='mountain'?1.5:1;out[r]+=Math.floor(base*bonus*assigned/2)}return out}
function guide(){if(owned()===9)return['Первое поручение','Нажми на клетку с золотой рамкой. Внизу карты появится кнопка присоединения.'];if(count('farm')<2)return['Наладь снабжение','Открой «Здания» и построй вторую ферму на свободной зелёной клетке.'];if(s.day<3)return['Проверь экономику','Нажми «Завершить день» справа и проверь изменения ресурсов.'];if(army()<5)return['Укрепи гарнизон','Открой вкладку «Армия» и найми ещё одного воина.'];return['Расширяй королевство','Захвати 15 земель, собери 12 воинов, вырасти население до 25 и возьми крепость справа.']}
function tabSelect(value){tab=value;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.section').forEach(e=>e.classList.toggle('active',e.id==='tab-'+tab))}
function modeSelect(value){mode=value;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));render()}
function render(){for(const k of ['day','gold','wood','stone','food','pop'])$(k).textContent=s[k];$('happy').textContent=s.happy+'%';$('housing').textContent=housing();$('army').textContent=army();$('lands').textContent=owned();$('stage').textContent=s.pop>=30?'Город':s.pop>=18?'Посёлок':'Деревня';$('modeName').textContent=mode==='build'?'Строительство':mode==='inspect'?'Осмотр':'Захват';
const gd=guide();$('guideTitle').textContent=gd[0];$('guideText').textContent=gd[1];for(const k of ['inf','arch','cav'])$(k).textContent=s.troops[k];$('armyCap').textContent=army()+'/'+armyMax();$('workers').textContent='Свободные: '+Math.max(0,s.pop-2-Math.min(s.tiles.filter(t=>t.owned&&['farm','lumber','quarry','market'].includes(t.building)).length*2,s.pop-2));
$('economy').replaceChildren();const inc=economy();for(const [k,v] of Object.entries(inc)){let d=document.createElement('div');d.className='listline';d.innerHTML='<span>'+({gold:'Золото',wood:'Дерево',stone:'Камень',food:'Еда'}[k])+'</span><b class="'+(v<0?'negative':'positive')+'">'+(v>0?'+':'')+v+'</b>';$('economy').appendChild(d)}
const goals=[[owned()>=15,'15 земель'],[s.pop>=25,'25 жителей'],[army()>=12,'12 воинов'],[s.tiles.some(t=>t.fortress&&t.owned),'Вражеская крепость']];$('goals').replaceChildren();goals.forEach(([done,t])=>{let d=document.createElement('div');d.className='listline';d.textContent=(done?'✅ ':'⬜ ')+t;$('goals').appendChild(d)});if(goals.every(g=>g[0])&&!s.won){s.won=true;log('Королевство победило!');message('🏆 Все цели выполнены!')}
$('nextDay').disabled=!!battle;draw();renderSelection();renderBuildings();renderRecruits()}
function renderBuildings(){$('buildings').replaceChildren();for(const [key,d] of Object.entries(defs)){let p=document.createElement('div');p.className='item'+(build===key?' selected':'');let top=document.createElement('div');top.className='itemtop';let title=document.createElement('strong');title.textContent=d.icon+' '+d.name;let cost=document.createElement('span');cost.className='minor';cost.textContent=price(d.cost);top.append(title,cost);let desc=document.createElement('small');desc.textContent=d.desc;let b=document.createElement('button');b.textContent=build===key&&mode==='build'?'Выбрано — нажми на карту':'Выбрать здание';b.disabled=!afford(d.cost);b.onclick=()=>{build=key;modeSelect('build');message('Выбрано: '+d.name+'. Нажми на свободную зелёную клетку.')};p.append(top,desc,b);$('buildings').appendChild(p)}}
function renderRecruits(){$('recruits').replaceChildren();for(const [k,label] of [['inf','Пехотинец'],['arch','Лучник'],['cav','Всадник']]){let c=hirePrice(k),p=document.createElement('div');p.className='item';p.innerHTML='<div class="itemtop"><strong>'+label+'</strong><span class="minor">'+price(c)+'</span></div>';let b=document.createElement('button');b.textContent='Нанять';b.disabled=!!battle||!afford(c)||army()>=armyMax();b.onclick=()=>{if(b.disabled)return;pay(c);s.troops[k]++;log('Нанят: '+label);message('Новый воин в армии.');render();save(false)};p.appendChild(b);$('recruits').appendChild(p)}}
function draw(){ctx.clearRect(0,0,900,600);ctx.textAlign='center';ctx.textBaseline='middle';let time=Date.now()/1000;for(const t of s.tiles){let x=t.x*C,y=t.y*C,nearby=near(t);ctx.fillStyle=t.owned?(t.terrain==='forest'?'#3d754d':t.terrain==='mountain'?'#707d63':'#508756'):t.enemy&&nearby?'#76504c':'#263e45';ctx.fillRect(x,y,C,C);ctx.strokeStyle=t.owned?'#9acfa1':'#4d6470';ctx.lineWidth=2;ctx.strokeRect(x+1,y+1,C-2,C-2);
if(t.owned){ctx.fillStyle='#ffffff18';for(let j=0;j<4;j++){ctx.beginPath();ctx.arc(x+18+j*20,y+15+(j%2)*57,2,0,7);ctx.fill()}ctx.font='32px serif';ctx.fillText(t.terrain==='forest'?'🌲':t.terrain==='mountain'?'⛰️':'🌿',x+50,y+51);if(t.building){ctx.fillStyle='#162a32bb';ctx.beginPath();ctx.roundRect(x+11,y+11,78,78,11);ctx.fill();ctx.font='51px serif';ctx.fillText(t.building==='hall'?'🏰':defs[t.building].icon,x+50,y+52)}}else{ctx.fillStyle=nearby?'#d5dca0':'#758c98';ctx.font='bold 30px system-ui';ctx.fillText(nearby?(t.fortress?'🏯':t.enemy?'⚔️':'?'):'·',x+50,y+50);if(nearby){ctx.strokeStyle=t.enemy?'#f4a98e':'#e9ce79';ctx.lineWidth=4;ctx.strokeRect(x+5,y+5,C-10,C-10)}}if(sel===t){ctx.strokeStyle='#fff2c0';ctx.lineWidth=5;ctx.strokeRect(x+4,y+4,C-8,C-8)}}
}
function renderSelection(){const title=$('tileTitle'),desc=$('tileDesc'),button=$('tileAction');button.hidden=true;button.onclick=null;if(!sel){title.textContent='Выбери клетку на карте';desc.textContent='Зелёные — свои, золотой контур — доступные земли.';return}
const t=sel;title.textContent=(t.owned?'Своя территория':'Чужая территория')+' · '+landNames[t.terrain];desc.textContent=t.building?(t.building==='hall'?'Столица — ратуша':defs[t.building].name):t.fortress?'Вражеская крепость':t.enemy?'Вражеский гарнизон':t.owned?'Свободная земля под строительство':near(t)?'Можно присоединить':'Слишком далеко для освоения';
if(battle)return;if(mode==='build'&&t.owned&&!t.building){const d=defs[build];button.hidden=false;button.disabled=!afford(d.cost);button.textContent='Построить '+d.name;button.onclick=()=>{if(!afford(d.cost))return;pay(d.cost);t.building=build;log('Построено: '+d.name);message('🏗️ '+d.name+' построено!');render();save(false)}}
if(mode==='expand'&&!t.owned&&near(t)){const cost={gold:22+Math.floor(owned()/6)*6,wood:12};button.hidden=false;button.disabled=!afford(cost)||(t.enemy&&army()===0);button.textContent=(t.enemy?'Атаковать':'Присоединить')+' · '+cost.gold+' зол.';button.onclick=()=>{if(!afford(cost))return;pay(cost);if(t.enemy){startBattle(t);message('⚔️ Сражение началось!')}else{t.owned=true;s.gold+=6;log('Присоединена земля');message('🚩 Территория присоединена!')}render();save(false)}}}
function select(t){sel=t;renderSelection();draw()}
function startBattle(t){let lv=t.fortress?5:Math.max(1,Math.floor((t.x+t.y)/3));battle={x:t.x,y:t.y,level:lv,guards:[12+lv*5,16+lv*6,10+lv*5]};unit='inf';$('battleDescription').textContent=t.fortress?'Штурм крепости. Уничтожь все отряды защитников.':'Бой за пограничные земли. Уничтожь всех защитников.';$('battleModal').classList.add('open');battleRender()}
function battleRender(){if(!battle)return;document.querySelectorAll('[data-unit]').forEach(b=>b.classList.toggle('active',b.dataset.unit===unit));$('enemyUnits').replaceChildren();['Стража','Воины','Стрелки'].forEach((name,i)=>{let d=document.createElement('div');d.className='statsblock';d.textContent=name+' · '+Math.max(0,Math.ceil(battle.guards[i]))+' здоровья';$('enemyUnits').appendChild(d)});document.querySelectorAll('[data-target]').forEach(b=>b.disabled=battle.guards[+b.dataset.target]<=0||s.troops[unit]<=0)}
function endBattle(win){const t=at(battle.x,battle.y);if(win){t.owned=true;t.enemy=false;let reward=t.fortress?180:45+battle.level*12;s.gold+=reward;s.stone+=t.fortress?70:12;log('Победа! +'+reward+' золота');message('🏆 Земля завоёвана!')}else{log('Отступление из битвы');message('🏳️ Отступление — пополни войска.')}battle=null;$('battleModal').classList.remove('open');render();save(false)}
function attack(i){if(!battle||s.troops[unit]<=0||battle.guards[i]<=0)return;let adv=unit==='inf'&&i===1||unit==='arch'&&i===0||unit==='cav'&&i===2;let damage=Math.round((unit==='inf'?18:unit==='arch'?21:27)*(adv?1.55:1));battle.guards[i]-=damage;if(battle.guards.every(g=>g<=0)){endBattle(true);return}const enemies=battle.guards.filter(g=>g>0).length;if(Math.random()<.08+enemies*.06+battle.level*.013){s.troops[unit]--; $('battleReport').textContent='Нанесено '+damage+' урона. Потерян один воин.'}else $('battleReport').textContent='Нанесено '+damage+' урона.'+(adv?' Сработало преимущество отряда!':'');if(army()===0){endBattle(false);return}battleRender();render()}
function day(){if(battle)return;s.day++;for(const [k,v] of Object.entries(economy()))s[k]=Math.max(0,s[k]+v);if(s.food===0){s.happy=Math.max(0,s.happy-12);s.pop=Math.max(3,s.pop-1);log('Голод в королевстве.')}else{if(s.day%2===0&&s.pop<housing()&&s.happy>=45){s.pop++;log('Прибыл новый житель')}s.happy=Math.min(100,s.happy+1)}if(s.day%7===0){let strength=Math.floor(s.day/7)+4,def=army()+count('barracks')*3;if(def<strength){s.gold=Math.max(0,s.gold-(strength-def)*12);log('Набег! Потеряно золото')}else{s.gold+=25;log('Набег отражён, +25 золота')}}message('☀️ Наступил день '+s.day);render();save(false)}
function save(show){try{localStorage.setItem(KEY,JSON.stringify({s,logs}));if(show)message('💾 Игра сохранена.')}catch(e){if(show)message('Сохранение недоступно в этом браузере.')}}
function fresh(){let tiles=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){let terrain=(x*13+y*7)%5===0?'mountain':(x*3+y*11)%4===0?'forest':'plain';tiles.push({x,y,terrain,owned:x>=1&&x<=3&&y>=2&&y<=4,building:null,enemy:[[5,1],[6,4],[7,2],[8,2]].some(([a,b])=>a===x&&b===y),fortress:x===8&&y===2})}s={day:1,gold:230,wood:140,stone:80,food:130,pop:12,happy:80,troops:{inf:3,arch:1,cav:0},tiles,won:false};at(2,3).building='hall';at(1,4).building='house';at(3,3).building='farm';at(2,2).building='lumber';mode='expand';build='farm';sel=null;battle=null;logs=[];log('Эльдория основана.');render();save(false)}
$('map').addEventListener('pointerdown',e=>{let rect=$('map').getBoundingClientRect(),x=Math.floor((e.clientX-rect.left)/rect.width*W),y=Math.floor((e.clientY-rect.top)/rect.height*H);if(valid(x,y))select(at(x,y))});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tabSelect(b.dataset.tab)));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>modeSelect(b.dataset.mode)));
document.querySelectorAll('[data-unit]').forEach(b=>b.addEventListener('click',()=>{unit=b.dataset.unit;battleRender()}));document.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>attack(+b.dataset.target)));$('retreat').addEventListener('click',()=>{if(battle)endBattle(false)});
$('guideButton').addEventListener('click',()=>{if(owned()===9){modeSelect('expand');message('Выбери клетку с золотой рамкой и нажми «Присоединить».')}else if(count('farm')<2){tabSelect('build');build='farm';modeSelect('build');message('Теперь нажми на свободную зелёную клетку.')}else if(s.day<3){message('Нажми «Завершить день» справа.')}else if(army()<5){tabSelect('army');message('Выбери воина для найма.')}else{modeSelect('expand');message('Продолжай расширять границы!')}});
$('nextDay').addEventListener('click',day);$('save').addEventListener('click',()=>save(true));$('reset').addEventListener('click',()=>{if(confirm('Начать новую игру и заменить сохранение?')){fresh();message('Начата новая игра.')}});
try{const raw=localStorage.getItem(KEY);if(raw){const v=JSON.parse(raw);if(v.s?.tiles?.length===W*H&&v.s.troops){s=v.s;logs=Array.isArray(v.logs)?v.logs:[];$('history').textContent=logs.join('\n');render();message('Сохранение загружено.')}else fresh()}else fresh()}catch(e){fresh()}
})();
